

# Site settings

title: Paxtan Laker
email: paxtanlaker@berkeley.edu
description: "A personal portfolio for Paxtan Laker: EECS UC Berkeley 2021. Playable demos, fun videos; check it out!"

theme: agency-jekyll-theme

# Team names, titles and social links
people:




- name: Paxtan Laker
  pic: 2
  position: 
  social:
    - title: github
      url: https://github.com/lakerpaxtan
    - title: linkedin
      url: https://www.linkedin.com/in/lakerpax/
    - title: facebook
      url: https://www.facebook.com/paxtan.laker



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty